controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    cmdvel_diffdrive_controller:
      type: my_robot_controllers/CmdVelDiffDriveController

cmdvel_diffdrive_controller:
  ros__parameters:
    left_wheel_joint: left_wheel_joint
    right_wheel_joint: right_wheel_joint
    wheel_radius: 0.10
    wheel_separation: 0.40
    cmd_timeout: 0.5
